#!/usr/bin/env bash

 if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
 fi

 username="$1"


 if id "$username" &>/dev/null; then
    # Run whoami under the specified user
    sudo -u "$username" whoami

 else
    echo "User '$username' does not exist."
    exit 1
