#!/usr/bin/env bash
#!/bin/bash

# Stop Nginx service
service nginx stop

# Modify Nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Modify Nginx configuration to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start

